### ISSUE TITLE
Background elements aren't blured

### ISSUE THREAD

**Issue by igor-tv** [ThrivingKings/animo.js#30]
Is it possible to blur the background element specified through css?
```css
.some-div {background: url (some-image.jpg)}
```
```javascript
$ ('. some-div'). animo ("blur");
```
Background aren't blur. Borders aren't blurred too.
Because of it is impossible to make blur the whole page, for example under the modal window.
